spring:
  application:
    name: ai-rag
  ai:
    ollama:
      chat:
        model: qwen3:8b
      embedding:
        model: mxbai-embed-large:335m

sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500.csv
